Use designated initialiser syntax for PyTypeObject
Fixes build with Clang. Switch to the more readable designated
initialiser syntax to avoid having to lookup member order.

Before, Clang would complain:
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -fPIC -I/usr/include/python3.10 -c patiencediff/_patiencediff_c.c -o build/temp.linux-x86_64-cpython-310/patiencediff/_patiencediff_c.o
patiencediff/_patiencediff_c.c:1175:5: error: incompatible pointer to integer conversion initializing 'Py_ssize_t' (aka 'long') with an expression of type 'void *' [-Wint-conversion]
    NULL, /* tp_print */
    ^~~~
/usr/include/wchar.h:46:14: note: expanded from macro 'NULL'
             ^~~~~~~~~~
```

This is because some of PyTypeObject's members are actually
Py_ssize_t so chucking a NULL in looks like a codesmell to Clang.

See https://docs.python.org/3/c-api/typeobj.html#quick-reference
and https://docs.python.org/3/c-api/typeobj.html#examples.

Bug: https://bugs.gentoo.org/869995
Closes: https://github.com/breezy-team/patiencediff/issues/12
Signed-off-by: Sam James <sam@gentoo.org>